### ISSUE TITLE
`processing-java` broken in macOS

### ISSUE THREAD

**Issue by rlfbckr** [processing/processing4#1045]
### Most appropriate sub-area of Processing 4?

Build process

### Processing version

4.4.1

### Operating system

MacOS 15.4.1

### Steps to reproduce this

install "processing-java"
run "processing-java" in terminal (error since 4.4.0, works with 4.3.4)

error message:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void processing.app.Base.setCommandLine()'
	at processing.mode.java.Commander.main(Commander.java:411)
```

### snippet

n/A

### Additional context

error message:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void processing.app.Base.setCommandLine()'
	at processing.mode.java.Commander.main(Commander.java:411)
```

### Would you like to work on the issue?

assigned to someone else.

**Comment by zjawj-123321** [comment]
使用下面命令重新创建 processing-java 的软链接（假设你放到 /Applications）：

sh
sudo ln -s /Applications/Processing.app/Contents/MacOS/processing-java /usr/local/bin/processing-java

更多：https://code.mayoubang.cn/conversion/share/41630234416

**Comment by rlfbckr** [comment]
Same problem with 4.4.0. Went back to 4.3.4.

**Comment by Stefterv** [comment]
Hi @rlfbckr Thank you for raising this issue! With 4.4.0 and 4.4.1 the internal layout of the Processing app changed somewhat, breaking the `processing-java`, sorry we didn't catch this in the Betas. 

I've created a PR above that will resolve this issue. It's probably going to be included in 4.4.3

**Comment by rlfbckr** [comment]
Thank you @Stefterv .
