### PR TITLE
Setup a Command Line Interface 

### LINKED ISSUE #1045: `processing-java` broken in macOS
### Most appropriate sub-area of Processing 4?

Build process

### Processing version

4.4.1

### Operating system

MacOS 15.4.1

### Steps to reproduce this

install "processing-java"
run "processing-java" in terminal (error since 4.4.0, works with 4.3.4)

error message:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void processing.app.Base.setCommandLine()'
	at processing.mode.java.Commander.main(Commander.java:411)
```

### snippet

n/A

### Additional context

error message:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void processing.app.Base.setCommandLine()'
	at processing.mode.java.Commander.main(Commander.java:411)
```

### Would you like to work on the issue?

assigned to someone else.

### LINKED ISSUE #1047: Snap does not have the commandline `processing-java` available
### Most appropriate sub-area of Processing 4?

Other (specify if possible)

### Processing version

4.4.1

### Operating system

Linux Ubuntu 24.04.2 LTS x86_64

### Steps to reproduce this

1. Install from source. See a binary called /path/to/source/processing-java. Run this binary with `--help`. It will show help, starting with

```
Command line edition for Processing 1295 (Java Mode)
```
(version will differ)

2. Now remove it and instead use the new snap to install. Run `snap info processing`

```
name:      processing
summary:   A friendly software sketchbook
....
commands:
  - processing
```

Notice there is no `processing-java`. 

running `snap run processing --help` launches the GUI an shows an error on the terminal, that --help is not recognized. 

###

Expected behaviour:
```bash
snap run processing-java
```
To run the CLI mode. E.g.

```bash
snap run processing-java --sketch /path/to/SomeSketch --run
```

To compile and run a sketch.

Offering the CLI in a separate snap would be fine as well. 

### snippet

Not applicable

### Additional context

_No response_

### Would you like to work on the issue?

No - I am unfamiliar with the build process of Processing, Gradle, Java

### PR DESCRIPTION
**Pull request by Stefterv**
This pull request will add command line arguments to the main Processing binary. Removing the need to publish separate binaries for additional functionality.

This will deprecate `processing-java` in favour of `processing cli` on linux.

Currently added functionality:
- `cli` Legacy hook for users of `processing-java`
- `lsp` Start the Language Server (for VSCode and Intellij)
-  More to come, feel free to suggest more tools that could be added. 

Fixes #1045 and Fixes #1047 

Screenshot 2025-04-18 at 17 43 42

### CODE REVIEW

**Comment by Stefterv** [comment]
Okay this is ready now.

Question, do we want to change this to provide `processing` on macOS instead of `processing-java`, in this way users on macOS can have access to Processing from the command line and not just the CLI, e.g. opening a Processing sketch by typing

    $ processing /path/to/sketch/sketch.pde

**Review by SableRaf — APPROVED** [review]
