### PR TITLE
fix for `java-processing` missing the necessary jars on macOS

### LINKED ISSUE #1045: `processing-java` broken in macOS
### Most appropriate sub-area of Processing 4?

Build process

### Processing version

4.4.1

### Operating system

MacOS 15.4.1

### Steps to reproduce this

install "processing-java"
run "processing-java" in terminal (error since 4.4.0, works with 4.3.4)

error message:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void processing.app.Base.setCommandLine()'
	at processing.mode.java.Commander.main(Commander.java:411)
```

### snippet

n/A

### Additional context

error message:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void processing.app.Base.setCommandLine()'
	at processing.mode.java.Commander.main(Commander.java:411)
```

### Would you like to work on the issue?

assigned to someone else.

### PR DESCRIPTION
**Pull request by Stefterv**
Fixes #1045

### CODE REVIEW

**Comment by Stefterv** [comment]
Superseded by #1050
