### PR TITLE
Adding `jdk.httpserver` as it was not included for the local reference

### LINKED ISSUE #1216: Local Reference not opening in 4.4.5 / 4.4.6 (NoClassDefFoundError: com.sun.net.httpserver.HttpHandler)
### Most appropriate sub-area of Processing 4?

Accessibility

### Processing version

4.4.6

### Operating system

Windows 11 Pro 64 bit

### Bug description

All worked on 4.4.4. After installing 4.4.6:
1. Help > Download Offline Reference
2. Help > Reference -> Now DO NOT opens LOCAL documentation, but returns ERROR:

```
Generated URL: https://github.com/processing/processing4/releases/download/processing-1306-4.4.6/processing-4.4.6-reference.zip
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/sun/net/httpserver/HttpHandler
	at processing.mode.java.JavaEditor.showReference(JavaEditor.java:850)
	at processing.mode.java.JavaEditor.lambda$buildHelpMenu$9(JavaEditor.java:306)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.net.httpserver.HttpHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
```

### Steps to reproduce this

1. Install Processing 4.4.6 on Windows.

2. From menu Help Download the local Reference

3. From Help menu try to open the Reference - see the ERROR in the log

### Would you like to work on the issue?

No, I’m just reporting the issue

### PR DESCRIPTION
**Pull request by Stefterv**
Adds the missing module for the local reference server

Closes #1216

### CODE REVIEW

**Comment by catilac** [comment]
@Stefterv this looks good to me, but I'm wondering how I can test it?

**Comment by Stefterv** [comment]
@catilac The CI has build a runnable version that can be downloaded here https://github.com/processing/processing4/actions/runs/17259348021?pr=1217

**Comment by Stefterv** [comment]
Another way to test it would be to check out the repo/branch and run the `runDistributable` task
